# Hardware configuration for proart (ASUS ProArt P16 OLED H7606WX-SE003X)
# Generated by nixos-generate-config, with hibernate support added
{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  # Initrd modules for ASUS ProArt P16
  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "thunderbolt" "usbhid" "uas" "sd_mod" "sdhci_pci" ];
  boot.initrd.kernelModules = [ ];

  # AMD Ryzen AI 9 HX 370 uses kvm-amd for virtualization
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  # === LUKS Encrypted Devices ===
  # Root partition
  boot.initrd.luks.devices."luks-acd6c1af-f1aa-4d25-bab3-0c87ce9cc0ec".device = "/dev/disk/by-uuid/acd6c1af-f1aa-4d25-bab3-0c87ce9cc0ec";

  # Swap partition (needed for hibernate)
  boot.initrd.luks.devices."luks-6599fe86-38a8-4bbe-9709-3c94a32312e3".device = "/dev/disk/by-uuid/6599fe86-38a8-4bbe-9709-3c94a32312e3";

  # === Filesystems ===
  fileSystems."/" = {
    device = "/dev/mapper/luks-acd6c1af-f1aa-4d25-bab3-0c87ce9cc0ec";
    fsType = "ext4";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/B683-D8FB";
    fsType = "vfat";
    options = [ "fmask=0077" "dmask=0077" ];
  };

  # === Swap & Hibernate ===
  swapDevices = [
    { device = "/dev/mapper/luks-6599fe86-38a8-4bbe-9709-3c94a32312e3"; }
  ];

  # Resume from hibernate
  boot.resumeDevice = "/dev/mapper/luks-6599fe86-38a8-4bbe-9709-3c94a32312e3";

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
