# Auto-generated by Forge during installation.
{ lib, ... }:

{
  forge.installer.username = "john";
  disko.devices.disk.main.device = lib.mkForce "/dev/nvme0n1";

  # Generated hibernate swap configuration
disko.devices.disk.main.content.partitions.luks.content.content.subvolumes."@swap" = {
mountpoint = "/swap";
mountOptions = [ "noatime" ];
swap.swapfile = {
      size = "191G";
      path = "swapfile";
};
};
zramSwap.enable = lib.mkForce false;

  boot.initrd.luks.devices."cryptroot".device = lib.mkForce "/dev/disk/by-uuid/24a77a29-837a-43a3-93e3-fc8383beeae8";

  boot.resumeDevice = lib.mkForce "/dev/mapper/cryptroot";
  boot.kernelParams = lib.mkAfter [ "resume_offset=533760" ];
}
