# Auto-generated by Forge during installation.
{ lib, ... }:

{
  forge.installer.username = "john";
  disko.devices.disk.main.device = lib.mkForce "/dev/disk/by-id/nvme-KXG80ZNV1T02_KIOXIA_45TA20GXKWTK";

  boot.initrd.luks.devices."cryptroot".device = lib.mkForce "/dev/disk/by-uuid/cd53ac94-ce67-4ed9-9bf6-4600033ab176";
}
