hl.on("hyprland.start", function()
  hl.exec_cmd([[systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP HYPRLAND_INSTANCE_SIGNATURE]])
  hl.exec_cmd([[dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP HYPRLAND_INSTANCE_SIGNATURE]])
  hl.exec_cmd([[sleep 1; systemctl --user restart xdg-desktop-portal-hyprland.service xdg-desktop-portal.service]])
  hl.exec_cmd([[systemctl --user start hyprland-session.target]])
end)
