#!/usr/bin/env bash
set -euo pipefail
cd -- "$(dirname -- "${BASH_SOURCE[0]}")"
sudo dnf -y upgrade --refresh
sudo flatpak update --system --noninteractive
exec ansible-playbook site.yml -e update_mode=true "$@"
