theme = "lumen"
close_when_open = true
click_to_close = true
single_click_activation = true
selection_wrap = true
hide_quick_activation = true
hide_action_hints = true
keybind_symbols = true
resume_last_query = false
ext_background_effect_blur = true

[placeholders]
"default" = { input = "Search apps, commands, files", list = "No results" }
"desktopapplications" = { input = "Search apps", list = "No apps found" }
"calc" = { input = "Calculate", list = "Type an expression" }
"files" = { input = "Search files", list = "No files found" }
"websearch" = { input = "Search the web", list = "Type a search" }

[providers]
default = ["desktopapplications", "calc", "websearch"]
empty = ["desktopapplications"]
max_results = 24
ignore_preview = ["desktopapplications", "calc", "websearch"]

[[providers.prefixes]]
prefix = ";"
provider = "providerlist"
[[providers.prefixes]]
prefix = ">"
provider = "runner"
[[providers.prefixes]]
prefix = "/"
provider = "files"
[[providers.prefixes]]
prefix = "."
provider = "symbols"
[[providers.prefixes]]
prefix = "="
provider = "calc"
[[providers.prefixes]]
prefix = "@"
provider = "websearch"
[[providers.prefixes]]
prefix = ":"
provider = "clipboard"
[[providers.prefixes]]
prefix = "$"
provider = "windows"
